### PR TITLE
Move code into package

### PR DESCRIPTION
**Pull request by joshrmcdaniel**
Setup `spotify_to_tidal` as a pypi package, adding some type hints

### CODE REVIEW

**Comment by timrae** [comment]
Why PR was closed? Let's use trunk based development?

**Comment by joshrmcdaniel** [comment]
I agree on that.  Currently the only branch is main, and I'm unsure of the branch workflow (i.e.: main -> test -> rc -> prod. etc), but we only have a `main` branch as the latest. We should tag the working releases at the least to ensure people know which branch/tag is stable to use

**Comment by timrae** [comment]
I like to keep it simple: create feature branches, open PR's for these, and merge them directly to main. Then create release tags off main every time there's a new package of work.

**Comment by joshrmcdaniel** [comment]
Sounds good. I created #34, it's this MR but to main

**Pull request closed without merging**
