### PR TITLE
 Continuous integration #50 

### PR DESCRIPTION
**Pull request by xerexcoded**
I have added a CircleCI configuration to this project, along with a few initial unit tests. This setup will ensure that our tests are automatically run on every commit.

### CODE REVIEW

**Comment by timrae** [comment]
Awesome, great start! Could you please fix the merge conflicts and cleanup the history so there's just a single commit without any merge commits?

**Comment by xerexcoded** [comment]
I have merged all the changes from your branch with my changes and squashed all of my commit messages to a single one https://github.com/spotify2tidal/spotify_to_tidal/pull/59/commits/4637103c6d97950c68d5f5b1610678bbad249d71

**Comment by timrae** [comment]
Hmm there are many commits showing not just a single one, perhaps you made an error with git? Could you please take a look?

**Comment by xerexcoded** [comment]
> Hmm there are many commits showing not just a single one, perhaps you made an error with git? Could you please take a look?

I thought squashing them would fix it, could you perhaps guide me to a resource that would help me to do this or maybe you could tell me how to do it?

**Comment by timrae** [comment]
I'm not sure exactly what you've done to get here, but probably this would fix it, assuming you've added this repo as your `upstream` remote 

```bash
git checkout main
git fetch upstream
git reset --hard upstream/main
git cherry-pick 4637103
git push origin HEAD -f
```

**Comment by xerexcoded** [comment]
Hey @timrae I have cleaned up the commit history in this commit https://github.com/spotify2tidal/spotify_to_tidal/pull/59/commits/2c4a7f340e88dd7111c3074587a4219f4d31cf86

**Comment by xerexcoded** [comment]
hey @timrae could you review my PR

**Review by timrae — APPROVED** [review]

**Pull request merged**
