### PR TITLE
Sync favorites

### PR DESCRIPTION
**Pull request by bloedboemmel**

### CODE REVIEW

**Comment by bastianandre** [comment]
It seems the SpotifyOAuth now also needs an additional 'user-top-read' scope to access the `/me/top/tracks`. Otherwise it fails with 403.

**Comment by timrae** [comment]
Hi thanks for your contribution, as I'm unable to commit the time to maintaining this repo by myself, I've decided to make a new public project. Please submit your PRs to the new project:
https://github.com/spotify2tidal/spotify_to_tidal

**Comment by timrae** [comment]
By the way, I'm really sorry that I never responded properly to this PR. Actually I would love to support this feature, I think it's a great improvement, however I wasn't really happy enough with the implementation to accept the PR, and didn't have the capacity at that time to explain what needed to change. In particular, there is a lot of logic that is copy-pasted from other parts of the code instead of refactoring the common functionality into reusable functions.

If you or anyone else is interested in re-implementing this feature, please let me know before you start working on it (e.g. in the #9 thread) and we can discuss what is the best approach to solving this problem. For example I would strongly recommend that we split up the existing `sync_playlist()` function into the parts that are common for both ordinary playlists and favourite tracks (e.g. something like `sync_tracks()`), and the rest which is specific to playlists. Then add a new function `sync_favourites()` which implements only the favourite specific logic, and calls the common function.

**Comment by timrae** [comment]
This feature is on `main` now, please test it and let us know any feedback

**Pull request closed without merging**
