### PR TITLE
Update sync.py - small fixes

### PR DESCRIPTION
**Pull request by RobinHirst11**
# what i updated:

- Fixed a few grammatical errors
- added an end when everything is synced
- fixed error with local files saved in playlists

### WIP, so here's a few of my future TODO:
- make a CLI ui, preferably things such as:
delete all tidal tracks
delete spotify tracks after transferred to tidal
enhanced logging in a txt file after complete
options to disable/enable "could not find track"
- make a webview where people can enter info and see transfers more visually, (for novices)
- in terminal, reset view so not cluttered up

### CODE REVIEW

**Comment by timrae** [comment]
Hi as I mentioned on another pr today, while I'm happy to accept small patches for bug fixes, I don't really have time to actively maintain this project or take on larger PRs, so if you're interested in maintaining the project then I'd recommend you create a fork and reach out for other collaborators, as I don't want to be a bottleneck for progress :)

**Comment by RobinHirst11** [comment]
yeah thats awesome!

**Comment by timrae** [comment]
Please submit PRs to the [new repo](https://github.com/spotify2tidal/spotify_to_tidal)

**Comment by timrae** [comment]
Nevermind, I decided to just move the repo instead of forking it

**Review by timrae — CHANGES_REQUESTED** [review]
Your second commit on this PR doesn't look right, you've added multiple main sections... Please try to make small clean commits that can be easily reviewed

**Pull request closed without merging**
